---
sidebar: sidebar 
permalink: reference_plan_ots_networking.html 
keywords: plan, planning, networking, network, drivers, vmxnet3, cluster mtu, firewall 
summary: Você deve configurar a rede do hypervisor corretamente antes de implantar o ONTAP Select. 
---
= Considerações de rede
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você deve configurar a rede do hypervisor corretamente antes de implantar o ONTAP Select.



== Opções de switch virtual

Você deve configurar um switch virtual em cada um dos hosts ONTAP Select para oferecer suporte à rede externa e à rede interna (somente clusters de vários nós). Como parte da implantação de um cluster de vários nós, você deve testar a conetividade de rede na rede interna do cluster.


NOTE: Para saber mais sobre como configurar um vSwitch em um host de hipervisor e o recurso de interface de alta velocidade, consulte a link:concept_nw_concepts_chars.html["Rede de mergulho profundo"]seção.



== Atualize para VMXNET3

A partir do ONTAP Select 9,5 usando o Deploy 2,10, o VMXNET3 é o driver de rede padrão incluído nas novas implantações de cluster no VMware ESXi. Se você atualizar um nó ONTAP Select mais antigo para a versão 9,5 ou posterior, o driver não será atualizado automaticamente.



== MTU do cluster

Uma rede interna separada é usada para conetar os nós do ONTAP Select em um cluster de vários nós. Normalmente, o tamanho da MTU para esta rede é 9000. No entanto, há situações em que esse tamanho de MTU é muito grande para a rede que coneta os nós de ONTAP Select. Para acomodar os quadros menores, o tamanho da MTU usado pelo ONTAP Select na rede interna pode estar no intervalo de 7500-9000 bytes.

O tamanho da MTU é exibido na seção Detalhes do cluster da página de criação do cluster. O valor é determinado pelo utilitário de administração de implantação da seguinte forma:

. Padrão inicial de 9000.
. À medida que você adiciona os hosts e redes para os pares de HA, o valor MTU é reduzido conforme necessário, com base na configuração dos vSwitches na rede.
. O valor final da MTU do cluster é definido depois de ter adicionado todos os pares de HA e estar pronto para criar o cluster.



NOTE: Você pode definir manualmente o valor MTU do cluster, se necessário, com base no design da sua rede.



== Host de duas NIC com vSwitch padrão

Para melhorar o desempenho do ONTAP Select em uma configuração de duas NIC, você deve isolar o tráfego de rede interno e externo usando dois grupos de portas. Esta recomendação se aplica à seguinte configuração específica:

* Cluster de vários nós ONTAP Select
* Duas NICs (NIC1 e NIC2)
* VSwitch padrão


Neste ambiente, você deve configurar o tráfego usando dois grupos de portas da seguinte forma:

.Grupo de portas 1
* Rede interna (cluster, RSM, tráfego HA-IC)
* O NIC1 está ativo
* NIC2 em modo de espera


.Grupo de portas 2
* Rede externa (dados e tráfego de gerenciamento)
* NIC1 está em espera
* NIC2 em ativo


Consulte link:concept_nw_concepts_chars.html["Rede de mergulho profundo"]a seção para obter mais informações sobre implantações de duas NIC.



== Host de quatro NIC com vSwitch padrão

Para melhorar o desempenho do ONTAP Select em uma configuração de quatro NIC, você deve isolar o tráfego de rede interno e externo usando quatro grupos de portas. Esta recomendação se aplica à seguinte configuração específica:

* Cluster de vários nós ONTAP Select
* Quatro NICs (NIC1, NIC2, NIC3 e NIC4)
* VSwitch padrão


Neste ambiente, você deve configurar o tráfego usando quatro grupos de portas da seguinte forma:

.Grupo de portas 1
* Rede interna (cluster, tráfego RSM)
* O NIC1 está ativo
* NIC2, NIC3, NIC4 em modo de espera


.Grupo de portas 2
* Rede interna (cluster, tráfego HA-IC)
* O NIC3 está ativo
* NIC1, NIC2, NIC4 em modo de espera


.Grupo de portas 3
* Rede externa (dados e tráfego de gerenciamento)
* O NIC2 está ativo
* NIC1, NIC3, NIC4 em modo de espera


.Grupo de portas 4
* Rede externa (tráfego de dados)
* O NIC4 está ativo
* NIC1, NIC2, NIC3 em modo de espera


Consulte link:concept_nw_concepts_chars.html["Rede de mergulho profundo"]a seção para obter mais informações sobre implantações de quatro NIC.



== Requisitos de tráfego de rede

Você deve certificar-se de que seus firewalls estão configurados corretamente para permitir que o tráfego de rede flua entre os vários participantes em um ambiente de implantação do ONTAP Select.

.Participantes
Existem vários participantes ou entidades que trocam tráfego de rede como parte de uma implantação do ONTAP Select. Estes são introduzidos e, em seguida, utilizados na descrição resumida dos requisitos de tráfego de rede.

* Implantar o utilitário de administração ONTAP Select Deploy
* VSphere/ESXi seja um servidor vSphere ou um host ESXi, dependendo de como o host é gerenciado na implantação do cluster
* Servidor de hipervisor host do hipervisor ESXi
* Nó OTS um nó ONTAP Select
* Cluster do OTS um cluster ONTAP Select
* Estação de trabalho administrativa local WS Admin


.Resumo dos requisitos de tráfego de rede
A tabela a seguir descreve os requisitos de tráfego de rede para uma implantação do ONTAP Select.

[cols="20,45,35"]
|===
| Protocolo / porta | Direção | Descrição 


| KIT DE PROTEÇÃO (443) | Implante no vCenter Server (gerenciado) ou ESXi (não gerenciado) | API VMware VIX 


| 902 | Implante no vCenter Server (gerenciado) ou ESXi (não gerenciado) | API VMware VIX 


| ICMP | Implantar no servidor do hipervisor | Ping 


| ICMP | Implante em cada nó do OTS | Ping 


| KIT DE MEIA (22) | Admin WS para cada nó do OTS | Administração 


| KIT DE PROTEÇÃO (443) | Implante em nós e clusters de OTS | Acesse o ONTAP 


| KIT DE PROTEÇÃO (443) | Cada nó do OTS a ser implantado | Acesse implantar 


| ISCSI (3260) | Cada nó do OTS a ser implantado | Disco de mediador/caixa de correio 
|===