---
sidebar: sidebar 
permalink: task_vpi_access.html 
keywords: vcenter, plug-in, vcenter plug-in, deploy plug-in, access, accessing 
summary: Você pode acessar o plug-in Deploy vCenter por meio do cliente da Web vSphere. 
---
= Acesse o plug-in do vCenter pelo vSphere
:allow-uri-read: 


[role="lead"]
Você pode acessar o plug-in Deploy vCenter por meio do cliente da Web vSphere.

.Antes de começar
O plug-in do vCenter deve estar instalado. Além disso, a conta do vCenter que você usa ao fazer login no vSphere deve ter o seguinte privilégio:

* NetApp
+
** ONTAP Select Deploy
+
*** Administrador






.Passos
. Saia do cliente da Web vSphere se você estiver conetado.
. Entre no vCenter usando o cliente da Web vSphere, selecione HTML5 e aceite o certificado SSL.
+
Fazer logout e voltar a fazer login atualiza as informações de configuração do vCenter.

. Clique em *Global Inventory Lists*.


.Resultado
As opções *clusters ONTAP Select* e *ONTAP Select Deploy* estão disponíveis no painel à esquerda. Se eles não forem exibidos, você deve sair e, em seguida, voltar a entrar.
