---
sidebar: sidebar 
permalink: task_install_deploy.html 
keywords: install, installing, ontap select deploy, deploy administration utility, deploy utility 
summary: Você precisa instalar o utilitário de administração ONTAP Select Deploy e usar o utilitário para criar um cluster do ONTAP Select. 
---
= Instale o ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você precisa instalar o utilitário de administração ONTAP Select Deploy e usar o utilitário para criar um cluster do ONTAP Select.



== Baixe a imagem da máquina virtual

Pode transferir o pacote ONTAP Select a partir do site de suporte da NetApp.

.Sobre esta tarefa
O utilitário de administração ONTAP Select Deploy é empacotado como uma máquina virtual (VM) baseada no padrão OVF (Open Virtualization Format). O único arquivo compactado tem o sufixo `ova`. A VM fornece o servidor de implantação e as imagens de instalação para nós do ONTAP Select.

.Passos
. Acesse o link:https://mysupport.netapp.com/site/["Site de suporte da NetApp"^] usando um navegador da Web e faça login.
. Selecione *Downloads* no menu e, em seguida, selecione *Downloads* no menu suspenso.
. Na página Downloads, em todos os produtos A-Z, selecione a letra *o*.
. Role para baixo e selecione *ONTAP Select*.
. Selecione a versão desejada do pacote.
. Reveja o Contrato de Licença de Utilizador final (EULA) e selecione *Accept & continue* (aceitar e continuar).
. Selecione e baixe o pacote apropriado, respondendo a todas as solicitações, conforme necessário.




== Verifique a assinatura OVA de implantação do ONTAP Select

Você deve verificar a assinatura do ONTAP Select Open Virtualization Appliance (OVA) antes de instalar o pacote de instalação.

.Antes de começar
Verifique se o sistema atende aos seguintes requisitos:

* OpenSSL versões 1.0.2 a 3,0 para verificação básica
* Acesso público à Internet para verificação de OCSP (Online Certificate Status Protocol)


.Passos
. Obtenha os seguintes arquivos na página de download do produto no site de suporte da NetApp:
+
[cols="2*"]
|===
| Ficheiro | Descrição 


| `ONTAP-Select-Deploy-Production.pub` | A chave pública usada para verificar a assinatura. 


| `csc-prod-chain-ONTAP-Select-Deploy.pem` | A cadeia de confiança da autoridade pública de certificação (CA). 


| `csc-prod-ONTAP-Select-Deploy.pem` | O certificado usado para gerar a chave. 


| `ONTAPdeploy.ova` | O executável de instalação do produto para ONTAP Select. 


| `ONTAPdeploy.ova.sig` | O algoritmo SHA-256 é hash e, em seguida, assinado pelo Remote Support Agent (RSA) usando a `csc-prod` chave e assinatura do instalador. 
|===
. Verifique se o `ONTAPdeploy.ova.sig` arquivo está usando os comandos de validação e certificados associados.
. Verifique a assinatura com o seguinte comando:
+
[listing]
----
openssl dgst  -sha256 -verify ONTAP-Select-Deploy-Production.pub -signature ONTAPdeploy.ova.sig  ONTAPdeploy.ova
----




== Implante a máquina virtual

Você deve instalar e iniciar a máquina virtual ONTAP Select Deploy usando a imagem da máquina virtual OVF. Como parte do processo de instalação, você deve configurar a interface de rede para usar DHCP ou uma configuração IP estática.

.Antes de começar
Você deve se preparar para implantar a máquina virtual ONTAP Select Deploy:

* Ative a funcionalidade OVF no seu navegador instalando o plug-in de integração de cliente VMware ou executando configuração semelhante conforme necessário
* DHCP ativado no ambiente VMware se você atribuir dinamicamente um endereço IP à máquina virtual implantar


Você deve ter as informações de configuração a serem usadas ao criar a máquina virtual, incluindo o nome da máquina virtual, da rede externa e do nome do host. Ao definir uma configuração de rede estática, você precisa das seguintes informações adicionais:

* Endereço IP da máquina virtual de implantação
* Máscara de rede
* Endereço IP do gateway (roteador)
* Endereço IP do servidor DNS primário
* Endereço IP do segundo servidor DNS
* Domínios de pesquisa DNS


.Sobre esta tarefa
Se você usar o vSphere, o assistente implantar modelo OVF inclui um formulário para fornecer todas as informações de configuração de implantação, incluindo a configuração de rede. No entanto, se você optar por não usar este formulário, poderá usar o console da máquina virtual implantar para configurar a rede.

.Passos
. Acesse o cliente vSphere e faça login.
. Navegue até o local apropriado na hierarquia e selecione *Deploy OVF Template*.
. Selecione o ARQUIVO OVA e conclua o assistente Deploy OVF Template, selecionando as opções apropriadas para o seu ambiente.
+
Tem de definir a palavra-passe da conta de administrador. Você precisa fornecer essa senha ao fazer login no utilitário implantar.

. Depois que a máquina virtual for implantada, selecione a nova máquina virtual e ligue-a se ela ainda não estiver ligada com base na sua entrada no assistente de implantação.
. Se necessário, você pode configurar a rede de implantação usando o console da máquina virtual:
+
.. Clique na guia *Console* para acessar o shell de configuração do host ESXi e monitorar o processo de inicialização.
.. Aguarde o seguinte aviso:
+
Nome do host :

.. Digite o nome do host e pressione *Enter*.
.. Aguarde o seguinte aviso:
+
Forneça uma senha para o usuário admin:

.. Digite a senha e pressione *Enter*.
.. Aguarde o seguinte aviso:
+
Usar DHCP para definir informações de rede? [n]:

.. Digite *n* para definir uma configuração IP estática ou y para usar DHCP e pressione *Enter*.
.. Se você escolher uma configuração estática, forneça todas as informações de configuração de rede, conforme necessário.






== Faça login na interface da Web de implantação

Você deve fazer login na interface do usuário da Web para confirmar que o utilitário de implantação está disponível e executar a configuração inicial.

.Passos
. Aponte seu navegador para o utilitário implantar usando o endereço IP ou nome de domínio:
+
`\https://<ip_address>/`

. Forneça o nome e a senha da conta de administrador (admin) e inicie sessão.
. Se a janela pop-up *Welcome to ONTAP Select* for exibida, revise os pré-requisitos e selecione *OK* para continuar.
. Se essa for a primeira vez que você fizer login e não instalar o Deploy usando o assistente disponível com o vCenter, forneça as seguintes informações de configuração quando solicitado:
+
** Nova senha para a conta de administrador (necessária)
** AutoSupport (opcional)
** Servidor vCenter com credenciais de conta (opcional)




.Informações relacionadas
link:task_cli_signing_in.html["Faça login para implantar usando SSH"]
